name: Workflows, Jobs and Steps

on: 
  workflow_dispatch:

jobs:
  job-1:
     runs-on: ubuntu-24.04
     steps: 
       - run: echo "This is the fist jobs where the workflow runs"
       - run: echo "Is this jobs runs single"

  job-2:
     runs-on: ubuntu-24.04
     steps:
       - run: echo "this jobs does not rely on other jobs!"

  job-3:
     runs-on: ubuntu-24.04
     needs:
       - job-1
       - job-2

  job-4:
     runs-on: ubuntu-24.04
     needs:
       - job-3
       - job-1
     steps:
       - run: echo "this is the last jobs that is depend on the job-3 and job1"
     
